name: Leafy Docker Image Build And Push CI  

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Node.js Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./leafy-frontend
          push: false
          tags: devwikirepo/leafy-frontend:${{ github.sha }}
          load: true

      - name: Build and push Spring Boot Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./leafy-backend
          push: false
          tags: devwikirepo/leafy-backend:${{ github.sha }}
          load: true